---
- hosts: localhost
  gather_facts: false
  become: true
  tasks:
     - name: install nginx
       apt:
         name: nginx
         state: latest
     - name: enabling nginx
       service:
           name: nginx
           enabled: yes

     - name: start nginx
       service:
            name: nginx
            state: started

