version: "3.8"

services:
     mysql:
         image: mysql:5.7
         volumes:
            - db_data:/var/lib/mysql
         restart: always
         environment:
               MYSQL_ROOT_PASSWORD: admin
               MYSQL_DATABASE: wordpress
               MYSQL_USER: khann-adill
               MYSQL_PASSWORD: pyrus@1806
     wordpress:
           depends_on:
               - mysql
           image: wordpress:latest
           ports:
            - "8080:80"
           restart: always
           environment:
                WORDPRESS_BD_HOST: mysql:3306
                WORDPRESS_DB_USER: khann-adill
                WORDPRESS_DB_PASSWORD: pyrus@1806
                WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
