---
name: Build the Ansible Docker Image

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * 0"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build . -t mak1806/ansible:1 -f tutorial/ansible/Dockerfile

      - name: Run the built image.
        run: docker run -itd --name ansible mak1806/ansible:1

      - name: Verify Ansible is accessible in the built image.
        run: docker exec -it ansible ansible --version
